name: Build

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0
