name: Build

on:
  workflow_dispatch:
  push:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04,macos-13,macos-14,windows-2019]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
            CIBW_ARCHS_LINUX: x86_64
            CIBW_ARCHS_WINDOWS: AMD64
            CIBW_SKIP: "*musllinux*"
            CIBW_BUILD_VERBOSITY: 1
            CIBW_BEFORE_ALL: bash .github/workflows/prebuild.sh
            CIBW_BEFORE_ALL_WINDOWS: powershell .github/workflows/prebuild_win.bat AMD64
            CIBW_ENVIRONMENT: >
                FETCH_DEPENDENCIES=OFF CMAKE_PREFIX_PATH=be/install

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        path: dist/*.tar.gz

  upload_all:
    needs: [build_wheels, make_sdist]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
