name: Build

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04,macos-13,macos-14,windows-2019]
        include:
          - os: windows-2019
            arch: AMD64
          - os: windows-2019
            arch: x86
          - os: ubuntu-20.04
            arch: x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
            CIBW_ARCHS_LINUX: ${{ matrix.arch }}
            CIBW_ARCHS_WINDOWS: ${{ matrix.arch }}
            CIBW_SKIP: "*musllinux*"
            CIBW_BUILD_VERBOSITY: 1
            CIBW_BEFORE_ALL: bash .github/workflows/prebuild.sh
            CIBW_BEFORE_ALL_WINDOWS: powershell .github/workflows/prebuild_win.bat ${{ matrix.arch }}
            CIBW_ENVIRONMENT: >
                FETCH_DEPENDENCIES=OFF CMAKE_PREFIX_PATH=be/install

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl