name: Build

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]

    env:
        CIBW_ARCHS_LINUX: x86_64
        CIBW_BUILD_VERBOSITY: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
            CIBW_ARCHS_LINUX: x86_64
            CIBW_BUILD_VERBOSITY: 1
            CIBW_BEFORE_ALL: bash .github/workflows/prebuild.sh
            CIBW_BEFORE_ALL_WINDOWS: powershell .github/workflows/prebuild_win.bat
            CIBW_ENVIRONMENT: FETCH_DEPENDENCIES=OFF CMAKE_PREFIX_PATH=be/install/lib/cmake/ITK-5.2:be/install/lib/cmake/Convert3D